# 10. Sorting and search

## Bubble sort

In [22]:
# Fun implementation
# Good:
# + end when no swaps (if sorted, then return)
# - check n elements each iteration (last of them are sorted already)
def bubble_sort(a):
    was_swap = True
    while was_swap:
        was_swap = False
        for i in range(1, len(a)):
            if a[i-1] > a[i]:
                a[i-1], a[i] = a[i], a[i-1]
                was_swap = True
    return a

In [12]:
# better implementation
# second dimension of algo is reduced by every iteration by first dimension
def bubble_sort_v2(a):
    n = len(a)
    for i in range(n-1): # [0, n-2]
        was_swap = False
        for j in range(n-1-i): # i= 0 j = [0, n-2], i = n-2 j = [0]
            if a[j] > a[j+1]:
                a[j], a[j+1] = a[j+1], a[j]
                was_swap = True
        if not was_swap:
            return

## Selection sort

In [15]:
def selection_sort(a):
    n = len(a)
    for i in range(n-1):
        min_idx = i
        for j in range(i+1, n):
            if a[j] < a[min_idx]:
                min_idx = j
        a[min_idx], a[i] = a[i], a[min_idx]
    return a

## Merge sort

In [31]:
# merge sort of array with indices in range [l, r)
def merge_sort(a, l, r):
    if r - l > 1:
        m = (l+r) // 2
        merge_sort(a, l, m) # [l, m)
        merge_sort(a, m, r) # [m. r)
        merge(a, l, m, r)

def merge(a, l, m, r):
    merged = [] 
    i = l
    j = m
    while i+j < m+r:
        if j == r or (a[i] < a[j] and i < m):
            merged.append(a[i])
            i += 1
        else:
            merged.append(a[j])
            j += 1
    
    a[l:r] = merged

In [33]:
def merge_sort_wrapper(a):
    n = len(a)
    merge_sort(a, 0, n)

## Quick sort

In [165]:
def quicksort(a, l, r):
    if l < r:
        p = partition(a, l, r)
        quicksort(a, l, p-1)
        quicksort(a, p, r)

def partition(a, l, r):
    pivot = a[(l+r) // 2]
    while l <= r:
        while a[l] < pivot: 
            l+=1
        while a[r] > pivot: 
            r-=1
        if l <= r: # pivot element is moving
            a[l], a[r] = a[r], a[l]
            l += 1
            r -= 1
    return l

In [166]:
def quicksort_wrapper(a):
    quicksort(a, 0, len(a)-1)

## Bit by bit sorting

## Summary

In [1]:
# Create unsorted array
import random
def rand_array(n):
    return random.sample(range(n), n)

In [ ]:
import timeit
def test_sort(algo):
    a = rand_array(10**2)
    copy_a = a.copy() # a will be sorted
    
    start = timeit.time.time()
    algo(a)
    end = timeit.time.time()
    print("Time was {} s.".format(end-start))
    print("Correct algo? ", a == sorted(copy_a))

In [175]:
# test sorts
for sort in [bubble_sort, bubble_sort_v2, selection_sort, merge_sort_wrapper, quicksort_wrapper]:
    print(sort)
    test_sort(sort)

<function bubble_sort at 0x7f51303bb840>
Time was 0.0045278072357177734 s.
Correct algo?  True
<function bubble_sort_v2 at 0x7f51304eed08>
Time was 0.0027511119842529297 s.
Correct algo?  True
<function selection_sort at 0x7f51303bbb70>
Time was 0.0018911361694335938 s.
Correct algo?  True
<function merge_sort_wrapper at 0x7f51304eeea0>
Time was 0.0012943744659423828 s.
Correct algo?  True
<function quicksort_wrapper at 0x7f5128e26268>
Time was 0.0007619857788085938 s.
Correct algo?  True


# Tasks
## 10.1

In [12]:
# Idea is to start merge from end of a and b 
# In that case, highest elements in a will be moved to the end of a, 
# freeing the place for smaller elements from b or a
def merge(a: list, b: list):
    'a and b sorted, result is sorted merge of a and b'
    # Elements counts
    a_n = len(a) - len(b) 
    b_n = len(b)
    i = a_n-1
    j = b_n-1
    k = len(a) - 1
    while k >= 0:
        if (j >=0 and b[j] > a[i]) or i < 0:
            a[k] = b[j]
            j-=1
        elif j >= 0:
            a[k] = a[i]
            i-=1
        k-=1

In [28]:
n = 20
rand_arr = rand_array(n)
a = rand_arr[:n//2]
b = rand_arr[n//2:]

bubble_sort(a)
bubble_sort(b)

a += [None for i in range(n // 2)]
print('a:', a)
print('b:', b)

a: [0, 1, 3, 4, 6, 7, 11, 14, 18, 19, None, None, None, None, None, None, None, None, None, None]
b: [2, 5, 8, 9, 10, 12, 13, 15, 16, 17]


In [29]:
merge(a, b)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


Wow! This works!  
I guess:   
time: $O(len(a) + len(b))$  
memory: $O(len(a))$

### 10.2 Anagrams

In [14]:
anagrams = ['aba', 'baa', 'aab', 'bbbcv', 'cvbbb', 'aqe', 'qea', 'qee']

Метод cmp
```
Должен возвращать целое: 
отрицательное, если self < other; 
нуль, если self == other; 
положительноеa, если self > other.
```

In [13]:
sorted(anagrams)

['aab', 'aba', 'aqe', 'baa', 'bbbcv', 'cvbbb', 'qea', 'qee']

In [4]:
anagrams.sort(key=lambda s: sorted(s))

In [5]:
anagrams

['aba', 'baa', 'aab', 'aqe', 'qea', 'bbbcv', 'cvbbb', 'qee']

In [12]:
# We should only group anagrams, right?
def sort(array: list):
    anagrams = {}
    for s in array:
        alphas = "".join(sorted(s))
        if alphas not in anagrams:
            anagrams[alphas] = []
        anagrams[alphas].append(s)
    
    i = 0
    for anagram in sorted(anagrams.keys()):
        for word in anagrams[anagram]:
            array[i] = word
            i+=1
    return array

In [15]:
sort(anagrams)

['aba', 'baa', 'aab', 'aqe', 'qea', 'bbbcv', 'cvbbb', 'qee']

### 10.3 Shifter array bin search (wrong solution. Only for ranges)

In [7]:
def search_in_shifted(a: list, x):
    '''a is a cyclically shifted sorted array of n int values in range [1, n]
    Last circumstance allows us to use binsearch to find x'''
    # find start of shifted sorted array
    n = len(a)
    lasts = n - a[0]
    min_i = (0 + lasts) % n
    
    # Convert indexation from [0, n-1) 
    # to cyclic range [min_idx, (min_idx + n)]
    new_idx = lambda i : (min_i + i) % n
    # Bin search
    l = 0
    r = n # Whyyyy? 
    
    while r - l > 1:
        m = (l + r) // 2
        shifted_m = new_idx(m)
        if x < a[shifted_m]:
            r = m
        else:
            l = m
    
    if a[new_idx(l)] == x:
        return new_idx(l)
    else:
        return None

In [18]:
n = 30
a = list(range(1, n))

num_shifts = 10
for _ in range(num_shifts):
    a.insert(0, a.pop())

print(a)

[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]


In [25]:
all([a.index(i) == search_in_shifted(a, i) for i in range(1, n-1)])

True

In [27]:
search_in_shifted(a, n-1) != None

False

Seems like it **almost** correct algo. But many possible bags. Like if there numeration starts from 0, not from 1 or numbers are negative

In [156]:
# If zero is first number
order_of_num = (a[0] + 1)
print(order_of_num, 'th')
# Last one is max. min will be after it. Maybe in first part of array so %
how_many_lasts = n - order_of_num 
print(how_many_lasts) 
# after a[0] 9 more numbers and 10th is min
min_idx = ((how_many_lasts) + 1) % n

21 th
9


In [169]:
#if one is first number
lasts = n - a[0]
min_idx = (0 + lasts) % n # First element and lsts elements after it
print(min_idx)
print(a[min_idx] == 1)

10
True


Algo is so tricky with indices. I'm so tired of that

In [37]:
search_in_shifted([15,16,19,20,25,1,3,4,5,7,10,14], 5)

It doesn't work for test case from book. Seems wrong approach to me. Let's fix it.

In [16]:
def find_split(a: list):
    '''a is sorted shifted array
    aim is to find split of it where left el is max and right is min
    '''
    
    l = 0
    r = len(a) -1
    
    while r-l > 1:
        m = (l+r) // 2
        if a[m] > a[r]: # split is between m and r
            l = m
        elif a[l] > a[m]: # split is between l and m
            r = m
        else: # no split found. array was not shifted
            break 
    return l, r

In [52]:
a = [15,16,19,20,25,1,3,4,5,7,10,14]
find_split(a)

(4, 5)

In [53]:
a = [1,2,3,4]
find_split(a)

(0, 3)

In [65]:
a = [4,1,2,3]
find_split(a)

(0, 1)

In [17]:
a = [1,1,1,1,1,1,1]
find_split(a)

(0, 6)

Ok, we found it! And can use idea from prev submission. But what about make solution easier and search x while searching split?

In [77]:
def search_in_shifted(a: list, x):
    split = find_split(a)
    if a[split[0]] < a[split[1]]:
        real_l = split[0]
    else:
        real_l = split[1]
    new_idx = lambda i: (real_l + i) % len(a)
    
    l = 0
    r = len(a)  
    while r - l > 1:
        m = (l + r) // 2
        if x < a[new_idx(m)]:
            r = m
        else:
            l = m
    
    if a[new_idx(l)] == x:
        return new_idx(l)
    else:
        return None

In [78]:
a = [15,16,19,20,25,1,3,4,5,7,10,14]

In [79]:
search_in_shifted(a, 5)

8

Time complexity $O(log_2n)$

### 10.4 Sort

Solution for 16 Gb

![][1]

[1]: https://cdn.pbrd.co/images/GLlOXT6.png

### 10.5 Search string in array

It's time to loo at search algorhyrtms from Levitin book

In [200]:
# Not nice enough algorhytm but works
def find_str(array: list, l: int, r: int, s: str):
    if r-l <= 2:
        if array[l] == s:
            return l
        elif array[r] == s:
            return r
        else:
            return None
    
    m = (l+r) // 2
    if array[m] == '':
        l_i = find_str(array, l, m-1, s)
        if l_i is not None:
            return l_i
        else:
            r_i = find_str(array, m+1, r, s)
            return r_i 
    elif array[m] == s:
        return m
    elif s < array[m]:
        return find_str(array, l, m-1, s)
    elif array[m] > s:
        return find_str(array, m+1, r, s)

In [201]:
# This one not works
def find_str_v2(array: list, l: int, r: int, s: str):
    if r-l <= 1:
        if array[l] == s:
            return l
        
    m = (l+r) // 2
    mid_s = array[m]
    if mid_s == '':
        l_i = find_str(array, l, m, s)
        if l_i is not None:
            return l_i
        else: 
            r_i = find_str(array, m+1, r, s)
            return r_i
    elif s < mid_s:
        return find_str(array, l, m, s)
    elif s > mid_s:
        return find_str(array, m, r, s)

In [196]:
a = ['at', 'ball', 'car', 'dad']

In [110]:
def joinit(iterable, delimiter_iterable):
    it = iter(iterable)
    yield next(it)
    for x in it:
        for d in delimiter_iterable:
            yield d
        yield x

In [ ]:
sorted_with_spaces = list(joinit(a, ['', '']))
print(sorted_with_spaces)

In [202]:
find_str(sorted_with_spaces, 0, len(sorted_with_spaces), 'car')

6

In [204]:
almost_empty = [''] * 10 + ['aa']
print(almost_empty)

['', '', '', '', '', '', '', '', '', '', 'aa']


In [211]:
find_str(almost_empty, 0, len(almost_empty), 'aa')

IndexError: list index out of range

### 10.6 Matrix bin search

In [18]:
import numpy as np

In [19]:
n, m = 3, 4
el = 3

In [20]:
mat = np.arange(n*m, dtype=int).reshape([n, m])

In [21]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
mat[0]

array([0, 1, 2, 3])

In [23]:
def is_sorted(a):
    return all(a[i] > a[i-1] for i in range(1, len(a)))

In [248]:
is_sorted(mat[0])

True

In [249]:
is_sorted(mat[:, 0])

True

In [24]:
def binsearch(seq, el):
    l = 0
    r = len(seq)
    
    while r-l > 1:
        m = (l+r) // 2
        if el < seq[m]:
            r = m
        else:
            l = m
    return l

In [25]:
def binsearch_in_mat(m, el):
    row = binsearch(m[:, 0], el)
    col = binsearch(m[row], el)
    
    if m[row, col] == el:
        return row, col
    else:
        return None, None

In [26]:
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [258]:
binsearch_in_mat(mat, 0)

(0, 0)

In [259]:
binsearch_in_mat(mat, 9)

(2, 1)

In [260]:
binsearch_in_mat(mat, 11)

(2, 3)

Works fine in $O(log_2 n\,log_2 m)$

In [30]:
a = np.array([[15,20,40,85],
             [20,35,80,95],
             [30,55,95,105],
             [40,80,100,120]])

In [31]:
a

array([[ 15,  20,  40,  85],
       [ 20,  35,  80,  95],
       [ 30,  55,  95, 105],
       [ 40,  80, 100, 120]])

In [32]:
binsearch_in_mat(a, 11)

(None, None)

In [33]:
binsearch_in_mat(mat, 85)

(None, None)

Uuuups. Not so fine as expected

### 10.7 Pyramid

In [111]:
# Seems like simple sort
class Person:
    def __init__(self, ht, wt):
        self.height = ht
        self.weight = wt
    
    
    def __lt__(self, other):
        return (self.weight < other.weight and 
                self.height < other.height)
    
    def __gt__(self, other):
        return (self.weight > other.weight
                and self.height > other.height)
    
    @classmethod
    def from_input(cls):
        height, weight = map(int, input().split())
        return Person(height, weight)
    
    def __repr__(self):
        return "({}, {})".format(self.height, self.weight)

In [95]:
# Input
n = int(input())
people = []
for i in range(n):
    people.append(Person.from_input())

12
1 1
2 4
5 5
6 6
7 7
8 8
9 9
1 15
16 2
17 16
18 19
20 20


In [10]:
# Repeating - mother of learning
def merge_sort(a, l, r):
    if r - l > 1:
        m = (l+r) // 2
        merge_sort(a, l, m)
        merge_sort(a, m, r)
        merge(a, l, m, r)

def merge(a, l, m, r):
    merged = []
    i, j = l, m
    while i+j < m+r:
        if j == r or (i < m and a[i] < a[j]):
            merged.append(a[i])
            i += 1
        else:
            merged.append(a[j])
            j += 1
    a[l:r] = merged

In [112]:
people = [Person(p.height, p.weight) for p in people]

In [5]:
a = [1,5,8,3,2,8,0]

In [50]:
merge_sort(a, 0, len(a))

In [52]:
a

[0, 1, 2, 3, 4, 5]

---

In [107]:
# Algo itself
# Sort then calculate max height
merge_sort(people, 0, n)

In [99]:
people

[(1, 1),
 (16, 2),
 (1, 15),
 (2, 4),
 (5, 5),
 (6, 6),
 (7, 7),
 (8, 8),
 (9, 9),
 (17, 16),
 (18, 19),
 (20, 20)]

In [109]:
people.sort(key=lambda p: max(p.weight, p.height))

In [110]:
people

[(1, 1),
 (2, 4),
 (5, 5),
 (6, 6),
 (7, 7),
 (8, 8),
 (9, 9),
 (1, 15),
 (16, 2),
 (17, 16),
 (18, 19),
 (20, 20)]

I think will be enough to del people with w less than prev w but h is bigger or vice versa

In [86]:
class Pyramid:
    def __init__(self, collection):
        self.data = [[collection[0]], []]
        level_max = 2
        level_amount = 0
        for item in collection[1:]:
            self.data[-1].append(item)
            level_amount += 1
            if level_amount == level_max:
                self.data.append([])
                level_max += 1
                level_amount = 0

        if len(self.data[-1]) == 0:
            del self.data[-1]
    
    def get_children_ij(self, i, j):
        children = None
        if i+1 < len(self.data):
            children = [(i+1, j), (i+1, j+1)]
        return children
    
    def next_el_ij(self, i, j):
        if i < len(self.data):
            if j+1 < len(self.data[i]):
                return (i, j+1)
            elif i+1 < len(self.data):
                return (i+1, 0)
    
    def __setitem__(self, key, value):
        i, j = key
        self.data[i][j] = value
        
    def __getitem__(self, key):
        i, j = key
        return self.data[i][j]
        
    def __len__(self):
        return len(self.data)
    
    def __repr__(self):
        levels = []
        for level in self.data:
            levels.append(repr(level))
        return '\n'.join(levels)
    
    # We can also yield or implement next instead 
    # https://www.programiz.com/python-programming/iterator
    def __iter__(self): 
        return iter(self.data)

In [83]:
a = [1,2,3]

In [87]:
p = Pyramid(people)

In [82]:
for i in p:
    print(i)

[(56, 90)]
[(60, 95), (65, 100)]
[(68, 110), (70, 150), (75, 190)]


In [90]:
p.next_el_ij(1,1)

(2, 0)

This solution is quite scary:  
Check each parent and child that they are ok (child.weight > parent.weight and child.height > parent.height).
And if something went wrong, search in later elements for good one for this position). then move and delete last and continue.    

I think there is somewhere better solution with right sorting and then simple list checking.  
But how to check when: in one level can be 3 ecual elements, but at next level it can't be, because  
(child.weight == parent.weight and ...)
So we should know also at which level we are. Oh it probably can be done.

## 10.8 Number stream rank

It should be a Node tree from pointers, cause each node should know length of it's subtree.

rank of number:
* find vertex with number x
* get length of left subtree (all element smaller than x)

add number:
* as usual

In [145]:
# Hah! It's like a binary tree with elements counts
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
        self.size = 1
        self.amount = 1 
    
    # It is broken. Good idea but not a best implementation
    def insert(self, x):
        if x < self.value:
            if self.left:
                self.left.insert(x)
            else:
                self.left = Node(x)
        elif x > self.value:
            if self.right:
                self.right.insert(x)
            else:
                self.right = Node(x)
        elif x == self.value:
            self.amount += 1
        if self.value < x:
            self.size += 1
    
    def rank_of(self, x):
        if x < self.value:
            if self.left:
                return self.left.rank_of(x)
            else:
                return 0
        elif x > self.value:
            if self.right:
                return self.right.rank_of(x)
            else:
                return 0
        elif x == self.value:
            return self.size - 1
        else:
            return 0
    
    def __repr__(self):
        return '[{} < ({}x{}|{}) > {}]'.format(self.left, self.value, self.amount, self.size, self.right)

In [146]:
t = Node(5)

In [147]:
a = [1,4,4,5,9,7,13,3]

In [148]:
for i in a:
    t.insert(i)

In [149]:
t

[[None < (1x1|4) > [[None < (3x1|1) > None] < (4x2|1) > None]] < (5x2|4) > [[None < (7x1|1) > None] < (9x1|2) > [None < (13x1|1) > None]]]

In [128]:
t.rank_of(4)

2

Don't work because of case:  
```
 5
1
  3
```

RANK of number also is an index in sorted array =)